[[company]]
name = "About"
url = "about/"
weight = 1
[[company]]
name = "Press Relaases"
url = "about/"
weight = 2
[[company]]
name = "Environment"
url = "environment/"
weight = 3
[[company]]
name = "Privacy Policy"
url = "privacy/"
weight = 4

[[main]]
name = "Get Started"
url = "get-started/"
weight = 1
[[main]]
name = "How it Works"
url = "how-it-works/"
weight = 2
[[main]]
name = "Solutions"
url = "solutions/"
weight = 5
[[main]]
name = "Doctors"
url = "doctors/"
weight = 10
[[main]]
name = "Technology"
url = "technology/"
weight = 15
[[main]]
name = "About"
url = "#"
hasChildren = true
weight = 15
  [[main]]
  parent = "About"
  name = "Why Us"
  url = "why-us/"
  weight = 10
  [[main]]
  parent = "About"
  name = "About Us"
  url = "about-us/"
  weight = 15
  [[main]]
  parent = "About"
  name = "Locations"
  url = "locations/"
  weight = 25

[[quick_links]]
name = "Lift Tickets"
url = "#!"
weight = 1
[[quick_links]]
name = "Season Passes"
url = "#!"
weight = 2
[[quick_links]]
name = "Vacation Packages"
url = "#!"
weight = 3
