# main menu
[[main]]
name = "How it Works"
url = "how-it-works/"
weight = 1

[[main]]
name = "Solution"
weight = 2
hasChildren = true

[[main]]
parent = "Solution"
weight = 1
name = "Anti Aging"
url = "anti-aging/"

[[main]]
parent = "Solution"
weight = 2
name = "Brain Behavioral Health"
url = "brain-behavioral-health/"

[[main]]
parent = "Solution"
weight = 3
name = "Hormonal Balance"
url = "hormonal-balance/"

[[main]]
parent = "Solution"
weight = 4
name = "Pain Relief"
url = "pain-relief/"

[[main]]
parent = "Solution"
weight = 5
name = "Cellular Detoxification"
url = "cellular-detoxification/"

[[main]]
name = "Centers"
url = "centers/"
weight = 3

[[main]]
name = "Therapies"
url = "therapies/"
weight = 4

[[company]]
name = "About"
url = "about/"
weight = 1

[[company]]
name = "Press Relaases"
url = "about/"
weight = 2

[[company]]
name = "Environment"
url = "environment/"
weight = 3

[[company]]
name = "Privacy Policy"
url = "privacy/"
weight = 4

[[quick_links]]
name = "Lift Tickets"
url = "#!"
weight = 1

[[quick_links]]
name = "Season Passes"
url = "#!"
weight = 2

[[quick_links]]
name = "Vacation Packages"
url = "#!"
weight = 3
