[[company]]
name = "About"
url = "about/"
weight = 1
[[company]]
name = "Press Relaases"
url = "about/"
weight = 2
[[company]]
name = "Environment"
url = "environment/"
weight = 3
[[company]]
name = "Privacy Policy"
url = "privacy/"
weight = 4
[[main]]
hasChildren = true
name = "Solutions"
url = "solutions/"
weight = 2
[[main]]
name = "How it Works"
url = "how-it-works/"
weight = 1
[[quick_links]]
name = "Lift Tickets"
url = "#!"
weight = 1
[[quick_links]]
name = "Season Passes"
url = "#!"
weight = 2
[[quick_links]]
name = "Vacation Packages"
url = "#!"
weight = 3
