[[company]]
name = "About"
url = "https://tf-soulspring.netlify.app/about-us/"
weight = 1
[[company]]
name = "Doctors"
url = "https://tf-soulspring.netlify.app/our-doctors/"
weight = 2
[[company]]
name = "Technology"
url = "https://tf-soulspring.netlify.app/technology/"
weight = 3
[[company]]
name = "Privacy Policy"
url = "#"
weight = 4
[[main]]
name = "Why Us"
parent = "About"
url = "why-us/"
weight = 10
[[main]]
name = "Offerings"
url = "offering/"
weight = 5
[[main]]
name = "Get Started"
url = "get-started/"
weight = 1
[[main]]
name = "How it Works"
url = "how-it-works/"
weight = 2
[[main]]
name = "Supplements"
parent = "About"
url = "supplements/"
weight = 50
[[main]]
name = "Technology"
url = "technology/"
weight = 15
[[main]]
name = "Doctors"
url = "our-doctors/"
weight = 10
[[main]]
name = "Locations"
parent = "About"
url = "locations/"
weight = 25
[[main]]
name = "About Us"
parent = "About"
url = "about-us/"
weight = 15
[[quick_links]]
name = "Get Started"
url = "get-started/"
weight = 1
[[quick_links]]
name = "How It Works"
url = "how-it-works/"
weight = 2
[[quick_links]]
name = "Offerings"
url = "offering/"
weight = 3
[[quick_links]]
name = "Doctors"
url = "doctors/"
weight = "4"
[[quick_links]]
name = "About"
url = "why-us/"
weight = "5"
