contact_form_action = "#"
copyright = "© 2022 SoulSpring. All rights reserved."
custom_script = ""
favicon = "images/favicon.png"
footer_content = "Soul Spring is a global network of bio-wellness and detox centers. Our mission is to make bio-individualized wellbeing a reality for humanity."
google_tag_manager = ""
image_gallery = true
logo = "images/logo.png"
logo_text = "Soul Spring"
logo_webp = true
logo_width = "140px"
mainSections = ["blog"]
theme_copyright = true
[baidu]
analytics_id = ""
enable = false
[contact_info]
address = "25420 Kuykendahl Rd, Suite D800, The Woodlands, TX 77375"
email = "info@asoulspring.com"
mobile = "+1 832 529 3100"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[crisp_chat]
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d"
enable = false
[matomo]
enable = false
id = ""
url = ""
[metadata]
author = "Themefisher"
description = "This is meta description"
image = "images/favicon.png"
keywords = ["Boilerplate", "Hugo", "Themefisher", "GetHugoThemes"]
[navigation_button]
enable = true
hubspotFormId = "b5c47a27-5574-4611-a600-dc94aa6b18f3"
hubspotPortalId = "21439971"
label = "Free Consultation"
[plausible]
domain = ""
enable = false
[preloader]
enable = false
preloader = ""
[site_verification]
baidu = ""
bing = ""
facebook = ""
google = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
