# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#E86851"
color_secondary = "#5AA836"
color_tertiary = "#58CDE2"
body_color = "#fff"
text_color = "#726464"
text_dark = "#222222"
text_light = "#FFF9F9"
border_color = "#ACB9C4"
black = "#000"
white = "#fff"
dark = "#3D3D3D"
light = "#eee"

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.28" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_primary = "Crimson+Text:wght@600"
font_primary_type = "serif"            # [serif/sans-serif/cursive]
font_secondary = "Inter:wght@400;500;600;700;800"
font_secondary_type = "sans-serif"     # [serif/sans-serif/cursive]
font_tertiary = "Satisfy"
font_tertiary_type = "cursive"         # [serif/sans-serif/cursive]
font_icon = "Font Awesome 6 Free"      # https://fontawesome.com/v6.0/icons/


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
[[params.plugins.css]]
link = "plugins/odometer/odometer.css"

# JS Plugins
# [[params.plugins.js]]
# link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[params.plugins.js]]
link = "plugins/glightbox.js"
[[params.plugins.js]]
link = "plugins/odometer/odometer.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/lazy-loader.js"
[[params.plugins.js]]
link = "https://cpwebassets.codepen.io/assets/embed/ei.js"
attributes = "async"
